"""
Modular LLM provider system.
Architecture: BaseLLMProvider → GeminiProvider / GroqProvider → LLMServiceRegistry

To add a new provider:
  1. Create a new class inheriting BaseLLMProvider
  2. Implement call() and is_available()
  3. Register it at the bottom: registry.register(MyNewProvider())
  That's it. Nothing else changes.
"""
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional
from app.config import settings
from app.utils.helpers import estimate_tokens, truncate_text


# ─────────────────────────────────────────────
# Response dataclass
# ─────────────────────────────────────────────

@dataclass
class LLMResponse:
    content: str
    model: str
    provider: str
    prompt_tokens: int = 0
    completion_tokens: int = 0
    mock: bool = False
    error: Optional[str] = None
    latency_ms: int = 0
    raw: dict = field(default_factory=dict)


# ─────────────────────────────────────────────
# Abstract base class
# ─────────────────────────────────────────────

class BaseLLMProvider(ABC):
    provider_name: str = "base"
    supported_models: list[str] = []

    @abstractmethod
    async def call(
        self,
        model: str,
        messages: list[dict],
        max_tokens: int = 1024,
    ) -> LLMResponse:
        """Make a real or mock call to the LLM provider."""
        pass

    def is_available(self) -> bool:
        """Return True if this provider has a valid API key configured."""
        raise NotImplementedError

    def _mock_response(self, model: str, prompt_tokens: int) -> LLMResponse:
        """Return a standard mock response when no API key is set."""
        return LLMResponse(
            content="Mock response generated by TokenOps. Set your API key in .env for real responses.",
            model=model,
            provider=self.provider_name,
            prompt_tokens=prompt_tokens,
            completion_tokens=12,
            mock=True,
        )

    def _error_response(self, model: str, error: str) -> LLMResponse:
        """Return an error response with context."""
        return LLMResponse(
            content="",
            model=model,
            provider=self.provider_name,
            mock=False,
            error=error,
        )


# ─────────────────────────────────────────────
# Google Gemini Provider
# ─────────────────────────────────────────────

class GeminiProvider(BaseLLMProvider):
    provider_name = "google"
    supported_models = [
        "gemini-1.5-flash",
        "gemini-1.5-pro",
        "gemini-2.0-flash",
    ]

    def is_available(self) -> bool:
        return bool(settings.gemini_api_key and settings.gemini_api_key.strip())

    async def call(
        self,
        model: str,
        messages: list[dict],
        max_tokens: int = 1024,
    ) -> LLMResponse:
        # Build a simple prompt from messages
        prompt_text = self._messages_to_text(messages)
        prompt_tokens = estimate_tokens(prompt_text)
        start = time.time()

        # --- Mock mode ---
        if not self.is_available():
            resp = self._mock_response(model, prompt_tokens)
            resp.latency_ms = int((time.time() - start) * 1000)
            return resp

        # --- Real call ---
        try:
            import google.generativeai as genai
            genai.configure(api_key=settings.gemini_api_key)
            gemini_model = genai.GenerativeModel(model)

            # Convert messages to Gemini format
            history = []
            final_message = prompt_text

            for msg in messages[:-1]:
                role = "user" if msg.get("role") == "user" else "model"
                history.append({"role": role, "parts": [msg.get("content", "")]})

            if messages:
                final_message = messages[-1].get("content", "")

            chat = gemini_model.start_chat(history=history)
            result = chat.send_message(
                final_message,
                generation_config={"max_output_tokens": max_tokens},
            )

            content = result.text or ""
            completion_tokens = estimate_tokens(content)
            latency = int((time.time() - start) * 1000)

            return LLMResponse(
                content=content,
                model=model,
                provider=self.provider_name,
                prompt_tokens=prompt_tokens,
                completion_tokens=completion_tokens,
                mock=False,
                latency_ms=latency,
                raw={"candidates": len(result.candidates) if hasattr(result, "candidates") else 1},
            )

        except Exception as e:
            latency = int((time.time() - start) * 1000)
            resp = self._error_response(model, str(e))
            resp.latency_ms = latency
            return resp

    def _messages_to_text(self, messages: list[dict]) -> str:
        """Flatten messages to a single string for token estimation."""
        parts = []
        for msg in messages:
            role = msg.get("role", "user")
            content = msg.get("content", "")
            parts.append(f"{role}: {content}")
        return "\n".join(parts)


# ─────────────────────────────────────────────
# Groq Provider
# ─────────────────────────────────────────────

class GroqProvider(BaseLLMProvider):
    provider_name = "groq"
    supported_models = [
        "llama3-8b-8192",
        "llama3-70b-8192",
        "mixtral-8x7b-32768",
    ]

    def is_available(self) -> bool:
        return bool(settings.groq_api_key and settings.groq_api_key.strip())

    async def call(
        self,
        model: str,
        messages: list[dict],
        max_tokens: int = 1024,
    ) -> LLMResponse:
        prompt_text = " ".join(m.get("content", "") for m in messages)
        prompt_tokens = estimate_tokens(prompt_text)
        start = time.time()

        # --- Mock mode ---
        if not self.is_available():
            resp = self._mock_response(model, prompt_tokens)
            resp.latency_ms = int((time.time() - start) * 1000)
            return resp

        # --- Real call ---
        try:
            from groq import Groq
            client = Groq(api_key=settings.groq_api_key)

            completion = client.chat.completions.create(
                model=model,
                messages=messages,
                max_tokens=max_tokens,
            )

            content = completion.choices[0].message.content or ""
            usage = completion.usage

            latency = int((time.time() - start) * 1000)
            return LLMResponse(
                content=content,
                model=model,
                provider=self.provider_name,
                prompt_tokens=usage.prompt_tokens if usage else prompt_tokens,
                completion_tokens=usage.completion_tokens if usage else estimate_tokens(content),
                mock=False,
                latency_ms=latency,
                raw={"id": completion.id},
            )

        except Exception as e:
            latency = int((time.time() - start) * 1000)
            resp = self._error_response(model, str(e))
            resp.latency_ms = latency
            return resp


# ─────────────────────────────────────────────
# Registry — routes model names to providers
# ─────────────────────────────────────────────

class LLMServiceRegistry:
    def __init__(self):
        self._providers: dict[str, BaseLLMProvider] = {}

    def register(self, provider: BaseLLMProvider):
        """Register a provider. All its supported_models get mapped to it."""
        for model in provider.supported_models:
            self._providers[model] = provider

    def get_provider(self, model: str) -> Optional[BaseLLMProvider]:
        """Get the provider for a given model name."""
        return self._providers.get(model)

    def list_models(self) -> list[str]:
        return list(self._providers.keys())

    async def call(
        self,
        model: str,
        messages: list[dict],
        max_tokens: int = 1024,
    ) -> LLMResponse:
        """
        Route the call to the correct provider.
        Falls back to Groq cheapest model if model is unknown.
        """
        provider = self.get_provider(model)

        if provider is None:
            # Unknown model — fall back to cheapest available
            fallback_model = settings.default_cheap_model
            provider = self.get_provider(fallback_model)
            if provider is None:
                return LLMResponse(
                    content="Mock response generated by TokenOps",
                    model=model,
                    provider="mock",
                    mock=True,
                )
            model = fallback_model

        return await provider.call(model=model, messages=messages, max_tokens=max_tokens)


# ─────────────────────────────────────────────
# Module-level singleton
# Import this everywhere: from app.services.llm_service import registry
# ─────────────────────────────────────────────

registry = LLMServiceRegistry()
registry.register(GeminiProvider())
registry.register(GroqProvider())